default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USER") %>
  password: <%= ENV.fetch("DB_PASSWORD") %>

development:
  <<: *default
  database: connamara_test_development

test:
  <<: *default
  database: connamara_test_development

production:
  <<: *default
  database: connamara_test_production
